name: File Operations Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

jobs:
  push_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Push a File
        run: |
          echo "This is a new file." > python.py
          git config --global user.name "uditi-12"
          git config --global user.email "uditigupta12@gmail.com"
          git add newfile.txt
          git commit -m "Add python.py"
          git push origin main

  pull_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull a File
        run: |
          git fetch origin main
          git checkout main
          git pull origin main
          cat python.py 

  manual_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Dispatch
        run: echo "This job was manually triggered"
