# name: Python CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       # - name: Set up Python 3.9
#       #   uses: actions/setup-python@v4
#       #   with:
#       #     python-version: '3.9'

#       # - name: Install Dependencies
#       #   run: |
#       #     python -m pip install --upgrade pip
#       #     pip install -r requirements.txt

#       # - name: Run Tests
#       #   run: |
#       #     pytest

#   modify_code:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Modify Code
#         run: |
#           echo "# Sample Python code modification" > python.py
#           git config --global user.name "uditi-12"
#           git config --global user.email "uditigupta12@gmail.com"
#           git add python.py
#           git commit -m "Modify Python code"
#           git push origin main

#   pull_file:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Pull a File
#         run: |
#           git fetch origin main
#           git checkout main
#           git pull origin main
#           cat python.py 

#   manual_dispatch:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Manual Dispatch
#         run: echo "This job was manually triggered"
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Build and deploy
        run: |
          mkdir -p public
          cp python.py public/
          echo "simple-login-page" > CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true   # Forces a clean slate on the gh-pages branch
          keep_files: false
