name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest

  modify_code:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Modify Code
        run: |
          echo "# Sample Python code modification" > python.py
          git config --global user.name "uditi-12"
          git config --global user.email "uditigupta12@gmail.com"
          git add src/main.py
          git commit -m "Modify Python code"
          git push origin main

  commit_and_monitor:
    runs-on: ubuntu-latest
    needs: modify_code
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Commit and Monitor
        run: |
          echo "Monitoring the build after code modification..."
          git fetch origin main
          git checkout main
          git pull origin main
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest
